name: Test Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: node:20.7.0-alpine3.17

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd app/
          npm install

      - name: Run tests
        run: npm test
